name: XTC Pages

on:
  workflow_call:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build-pages:
    name: Build Pages preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: pip
      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)"
          pip list
      - name: Install XTC Package in dev mode
        run: |
          pip install -e .[dev]
      - name: Build Pages
        run: make pages
      - name: Upload Pages preview
        uses: actions/upload-artifact@v5
        with:
          name: pages-preview
          path: public/
          if-no-files-found: error

  deploy-pages:
    name: Deploy Pages
    if: startsWith(github.ref, 'refs/tags/xtc-v')
    needs: build-pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Pages preview
        uses: actions/download-artifact@v6
        with:
          name: pages-preview
          path: public/
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
